import Auth from '../components/elements/auth/auth'
import Head from 'next/head'
import { AppContext } from '../context/state';
import { useContext, useEffect } from 'react'
import { useRouter } from 'next/router'
import { useAuth
 } from '../context/auth';
export default function auth() {

  const { isAuthenticated, user, loading } = useAuth();

  const router = useRouter();

  useEffect(() => {
    if((isAuthenticated)){router.push("/")}
  }, [])
  if(!isAuthenticated){

    return (

      <>
      <Head>
        <title>Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
      <Auth />
    </>
    )
  }else {
    return null
  }
  

}
