import Auth from '../components/elements/auth/auth'
import Head from 'next/head'
import { AppContext } from '../context/state';
import { useContext } from 'react'
import Router from 'next/router';

export default function auth() {

  const authContext = useContext(AppContext);
  if(authContext.state.auth){
    Router.push("/");
  }else {
      return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Auth />
  </>
  )
  }

}
