import Layout from '../components/layout/layout'
import Home from '../components/elements/home/home'
import Head from 'next/head'


export default function home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Home />
      </Layout>
    </>
  )
}
